version: '3.9'

services:
  postgres_logs:
    image: postgres:15
    container_name: qdrant_logs_db
    ports:
      - "${PG_LOG_PORT_HOST}:5432"
    environment:
      POSTGRES_DB: ${PG_LOG_DB}
      POSTGRES_USER: ${PG_LOG_USER}
      POSTGRES_PASSWORD: ${PG_LOG_PASS}
    volumes:
      - ./pg_logs_data:/var/lib/postgresql/data
    command: postgres -c password_encryption=md5
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_LOG_USER} -d ${PG_LOG_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - bi_network

  # --- Qdrant ---
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_server
    ports:
      - "${QDRANT_HTTP_PORT}:6333"          # внешний порт для HTTP API
      - "${QDRANT_GRPC_PORT}:6334"          # внешний порт для gRPC
    volumes:
      - ./qdrant_storage:/qdrant/storage   # локальная папка для данных БД
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    networks:
      - bi_network

  # приложение
  app:
    build: .
    container_name: qdrant_app
    command: sh -c "python app.py"
    restart: always
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      postgres_logs:
        condition: service_healthy
      qdrant:
        condition: service_started  # Qdrant пока не имеет встроенного healthcheck, можно проверить через curl
    env_file:
      - .env
    networks:
      - bi_network

networks:
  bi_network:
    driver: bridge